---
kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: git
  pull: if-not-exists
  image: plugins/git
  settings:
    depath: 50
    tags: true

# - name: front
#   pull: if-not-exists
#   image: node:11.13.0
#   commands:
#   - yarn install
#   - yarn run prod
#   when:
#     branch:
#     - master
#     - dev

- name: scp
  pull: if-not-exists
  image: appleboy/drone-scp
  settings:
    host:
    - 143.198.208.10
    port: 22
    source:
    - Dockerfile
    - src
    target: /var/www/resume_stan
    username: stan
    envs:
      SSH_KEY:
        from_secret: ssh_key
  when:
    branch:
    - master
    - dev

# - name: ssh
#   pull: if-not-exists
#   image: appleboy/drone-ssh
#   settings:
#     host:
#     - 206.189.147.149
#     port: 22
#     script:
#     - rm -rf /var/www/resume && mkdir -p /var/www/resume
#     - cp -r /var/www/test/* /var/www/personalSite
#     - cd /var/www/personalSite/server && docker container rm -f server_maoweb_1  server_database_1 && docker-compose up -d
#     - cd /var/www/personalSite && pm2 restart process.json
#     username: stan
#   environment:
#     SSH_KEY:
#       from_secret: ssh_key